author:
  name: Eliezer Oliveira
  email: eliezerreis@gmail.com

server:
  port: 8080

spring:
  application:
    name: MagUsers
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info

csv:
  file:
    path: ${CSV_FILE_PATH:database/users.csv}