author:
  name: Eliezer Oliveira
  email: eliezerreis@gmail.com

server:
  port: 8080

spring:
  application:
    name: MagUsers

management:
  endpoints:
    web:
      exposure:
        include: health,info

csv:
  file:
    path: ${CSV_FILE_PATH:database/users.csv}