networks:
  magnetwork:
    driver: bridge

services:
  magusers:
    image: "mag/magusers:latest"
    networks:
      - magnetwork
    ports:
      - "8080"
    deploy:
      replicas: 3
    volumes:
      - ./database:/mnt
    environment:
      CSV_FILE_PATH: /mnt/users.csv
      SPRING_PROFILES_ACTIVE: dev

  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - magnetwork
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    networks:
      - magnetwork
    ports:
      - "5672:5672"
      - "15672:15672"